name: dart_learning_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^0.13.6
  json_serializable: ^6.6.2
  convert: ^3.1.1
dependencies:
  sqflite_common_ffi: ^2.2.5
  sqlite3: ^1.11.1
